// Stub type declarations for the test WASM package generated by:
//   wasm-pack build crates/photobook-core --target web --out-dir web/test-pkg --features wasm-test --dev
// The real .d.ts is produced at build time; this stub satisfies tsc at dev time.

export default function init(
  input?: string | URL | Request | BufferSource | WebAssembly.Module,
): Promise<unknown>;

export function init_panic_hook(): void;
export function wasm_test_list(): string;
export function wasm_test_run(name: string): void;
