// Tests for the JSON-parse wrappers in wasm-bridge.ts.
//
// The WASM module is mocked so tests run in Node without a browser or WASM runtime.
// Each test verifies that the bridge function correctly parses the JSON string returned
// by the editor method and exposes the expected fields.

import { describe, it, expect, vi } from 'vitest';

// ---------------------------------------------------------------------------
// vi.hoisted() lets us create the mock function before vi.mock() is applied.
// This is necessary because vi.mock() is hoisted but variable initialisers are not.
// ---------------------------------------------------------------------------

const { computeImageCoverMock } = vi.hoisted(() => ({
  computeImageCoverMock: vi.fn(() =>
    JSON.stringify({ sw: 200, sh: 150, overflow_x: 50, overflow_y: 25, pan_off_x: 25, pan_off_y: 12.5 }),
  ),
}));

// Mock the WASM module. The test file itself never imports from ./pkg/photobook_core.js
// directly (that file is generated by wasm-pack and won't exist in CI until after
// the build step). All access to compute_image_cover goes through computeImageCoverMock.
vi.mock('./pkg/photobook_core.js', () => ({
  PhotobookEditor: class {},
  compute_image_cover: computeImageCoverMock,
}));

import {
  getRenderList,
  getDividers,
  getSpreadInfo,
  getPageSizeMm,
  getAllSelected,
  getUsedImageIds,
  splitFaceForMultiDrop,
  computeImageCover,
  getFrameTransform,
  getLowDpiFrames,
  getResolvedSpreadDelta,
} from './wasm-bridge.js';

// ---------------------------------------------------------------------------
// Helper: build a minimal mock editor whose methods return valid JSON strings
// ---------------------------------------------------------------------------

function makeEditor(overrides: Record<string, (...args: unknown[]) => string> = {}): any {
  const defaults: Record<string, (...args: unknown[]) => string> = {
    get_render_list:            () => '[]',
    get_dividers:               () => '[]',
    get_low_dpi_frames:         () => '[]',
    get_all_selected:           () => '[]',
    get_used_image_ids:         () => '[]',
    split_face_for_multi_drop:  () => '[]',
    get_frame_transform:        () => JSON.stringify({ pan_x: 0.5, pan_y: 0.5, scale: 1.0, rotation_deg: 0.0 }),
    get_current_spread_info:    () => JSON.stringify({
      kind: 'content', width_mm: 420, height_mm: 297, spine_mm: 5.0,
      page_width_mm: 210, left_bg: '', right_bg: '', endpaper_side: null,
    }),
    get_page_size_mm:   () => JSON.stringify({ width_mm: 210, height_mm: 297 }),
    get_spread_margin:  () => JSON.stringify({ top: 0, right: 0, bottom: 0, left: 0 }),
    get_resolved_spread_delta: () => JSON.stringify({
      full: null, updated_frames: null, removed_frame_ids: null,
    }),
  };
  return { ...defaults, ...overrides };
}

// ---------------------------------------------------------------------------
// getRenderList
// ---------------------------------------------------------------------------

describe('getRenderList', () => {
  it('returns an empty array when the spread has no frames', () => {
    const frames = getRenderList(makeEditor(), 1000, 500);
    expect(Array.isArray(frames)).toBe(true);
    expect(frames.length).toBe(0);
  });

  it('parses frame objects and exposes all expected fields', () => {
    const frame = {
      id: 42,
      rect: { x: 0, y: 0, w: 500, h: 500 },
      face_rect: { x: 0, y: 0, w: 500, h: 500 },
      pan_x: 0.3, pan_y: 0.7, scale: 1.5, rotation_deg: 90.0,
      is_selected: true,
      object_fit: 'cover',
      border_width_top: 2, border_width_right: 2, border_width_bottom: 2, border_width_left: 2,
      border_color: '#ff0000', border_position: 'inner', border_radius: 4,
      face_rotation_deg: 0,
    };
    const editor = makeEditor({ get_render_list: () => JSON.stringify([frame]) });
    const frames = getRenderList(editor, 1000, 500);
    expect(frames.length).toBe(1);
    expect(frames[0].id).toBe(42);
    expect(frames[0].rect.w).toBe(500);
    expect(frames[0].pan_x).toBe(0.3);
    expect(frames[0].is_selected).toBe(true);
    expect(frames[0].border_color).toBe('#ff0000');
  });

  it('forwards canvas dimensions to the underlying method', () => {
    const spy = vi.fn(() => '[]');
    getRenderList(makeEditor({ get_render_list: spy }), 800, 600);
    expect(spy).toHaveBeenCalledWith(800, 600);
  });
});

// ---------------------------------------------------------------------------
// getDividers
// ---------------------------------------------------------------------------

describe('getDividers', () => {
  it('returns an empty array when there are no dividers', () => {
    expect(getDividers(makeEditor(), 1000, 500)).toEqual([]);
  });

  it('parses divider objects with expected fields', () => {
    const divider = { segment_id: 7, axis: 'h', x: 0, y: 250, length: 1000 };
    const editor = makeEditor({ get_dividers: () => JSON.stringify([divider]) });
    const dividers = getDividers(editor, 1000, 500);
    expect(dividers.length).toBe(1);
    expect(dividers[0].segment_id).toBe(7);
    expect(dividers[0].axis).toBe('h');
    expect(dividers[0].y).toBe(250);
  });
});

// ---------------------------------------------------------------------------
// getSpreadInfo
// ---------------------------------------------------------------------------

describe('getSpreadInfo', () => {
  it('returns a SpreadInfo with the correct shape', () => {
    const info = getSpreadInfo(makeEditor());
    expect(info.kind).toBe('content');
    expect(info.width_mm).toBe(420);
    expect(info.height_mm).toBe(297);
    expect(info.spine_mm).toBe(5.0);
    expect(info.page_width_mm).toBe(210);
    expect(info.endpaper_side).toBeNull();
  });

  it('propagates cover kind and non-null endpaper_side', () => {
    const editor = makeEditor({
      get_current_spread_info: () => JSON.stringify({
        kind: 'cover', width_mm: 425, height_mm: 297, spine_mm: 5.0,
        page_width_mm: 210, left_bg: '#fff', right_bg: '#000', endpaper_side: 'left',
      }),
    });
    const info = getSpreadInfo(editor);
    expect(info.kind).toBe('cover');
    expect(info.endpaper_side).toBe('left');
    expect(info.left_bg).toBe('#fff');
  });
});

// ---------------------------------------------------------------------------
// getPageSizeMm
// ---------------------------------------------------------------------------

describe('getPageSizeMm', () => {
  it('returns width_mm and height_mm', () => {
    const size = getPageSizeMm(makeEditor());
    expect(size.width_mm).toBe(210);
    expect(size.height_mm).toBe(297);
  });
});

// ---------------------------------------------------------------------------
// getAllSelected
// ---------------------------------------------------------------------------

describe('getAllSelected', () => {
  it('returns an empty array when nothing is selected', () => {
    expect(getAllSelected(makeEditor())).toEqual([]);
  });

  it('returns face IDs as numbers', () => {
    const editor = makeEditor({ get_all_selected: () => JSON.stringify([3, 7, 12]) });
    expect(getAllSelected(editor)).toEqual([3, 7, 12]);
  });
});

// ---------------------------------------------------------------------------
// getUsedImageIds
// ---------------------------------------------------------------------------

describe('getUsedImageIds', () => {
  it('returns an empty Set when no images are placed', () => {
    const set = getUsedImageIds(makeEditor());
    expect(set instanceof Set).toBe(true);
    expect(set.size).toBe(0);
  });

  it('returns a Set of the placed image IDs', () => {
    const editor = makeEditor({
      get_used_image_ids: () => JSON.stringify(['img-1.jpg', 'img-2.png']),
    });
    const set = getUsedImageIds(editor);
    expect(set.size).toBe(2);
    expect(set.has('img-1.jpg')).toBe(true);
    expect(set.has('img-2.png')).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// splitFaceForMultiDrop
// ---------------------------------------------------------------------------

describe('splitFaceForMultiDrop', () => {
  it('returns an array of face IDs', () => {
    const editor = makeEditor({
      split_face_for_multi_drop: () => JSON.stringify([1, 2, 3, 4]),
    });
    const ids = splitFaceForMultiDrop(editor, 0, 4, true);
    expect(ids).toEqual([1, 2, 3, 4]);
  });

  it('forwards all arguments to the underlying method', () => {
    const spy = vi.fn(() => JSON.stringify([5]));
    splitFaceForMultiDrop(makeEditor({ split_face_for_multi_drop: spy }), 5, 1, false);
    expect(spy).toHaveBeenCalledWith(5, 1, false);
  });
});

// ---------------------------------------------------------------------------
// getFrameTransform
// ---------------------------------------------------------------------------

describe('getFrameTransform', () => {
  it('parses a FrameTransform with default values', () => {
    const t = getFrameTransform(makeEditor(), 0);
    expect(t).not.toBeNull();
    expect(t!.pan_x).toBe(0.5);
    expect(t!.pan_y).toBe(0.5);
    expect(t!.scale).toBe(1.0);
    expect(t!.rotation_deg).toBe(0.0);
  });
});

// ---------------------------------------------------------------------------
// getLowDpiFrames
// ---------------------------------------------------------------------------

describe('getLowDpiFrames', () => {
  it('returns an empty array when no frames are low-DPI', () => {
    expect(getLowDpiFrames(makeEditor(), 1000, 500)).toEqual([]);
  });

  it('parses low-DPI frame entries with id and effective_dpi', () => {
    const editor = makeEditor({
      get_low_dpi_frames: () => JSON.stringify([{ id: 3, effective_dpi: 72 }]),
    });
    const frames = getLowDpiFrames(editor, 1000, 500);
    expect(frames.length).toBe(1);
    expect(frames[0].id).toBe(3);
    expect(frames[0].effective_dpi).toBe(72);
  });
});

// ---------------------------------------------------------------------------
// computeImageCover (free function wrapper)
// ---------------------------------------------------------------------------

describe('computeImageCover', () => {
  it('returns a parsed ImageCoverResult with the expected fields', () => {
    const result = computeImageCover(200, 150, 400, 300, 0.5, 0.5, 1.0, 0.0);
    expect(result).not.toBeNull();
    expect(result!.sw).toBe(200);
    expect(result!.sh).toBe(150);
    expect(result!.overflow_x).toBe(50);
    expect(result!.pan_off_x).toBe(25);
  });

  it('returns null when the WASM function returns the JSON string "null"', () => {
    computeImageCoverMock.mockReturnValueOnce('null');
    const result = computeImageCover(0, 0, 100, 100, 0.5, 0.5, 1.0, 0.0);
    expect(result).toBeNull();
  });

  it('forwards all eight arguments to the underlying WASM function', () => {
    computeImageCoverMock.mockClear();
    computeImageCover(100, 200, 300, 400, 0.1, 0.9, 1.5, 45.0);
    expect(computeImageCoverMock).toHaveBeenCalledWith(100, 200, 300, 400, 0.1, 0.9, 1.5, 45.0);
  });
});

// ---------------------------------------------------------------------------
// getResolvedSpreadDelta
// ---------------------------------------------------------------------------

describe('getResolvedSpreadDelta', () => {
  it('returns a SpreadDelta with null fields when nothing changed', () => {
    const delta = getResolvedSpreadDelta(makeEditor(), 1000, 500);
    expect(delta.full).toBeNull();
    expect(delta.updated_frames).toBeNull();
  });

  it('parses a full resolved spread when structure is dirty', () => {
    const fullSpread = {
      frames: [{ id: 1, rect: { x: 0, y: 0, w: 1000, h: 500 } }],
      dividers: [],
      twin_handles: [],
    };
    const editor = makeEditor({
      get_resolved_spread_delta: () => JSON.stringify({
        full: fullSpread,
        updated_frames: null,
        removed_frame_ids: null,
      }),
    });
    const delta = getResolvedSpreadDelta(editor, 1000, 500);
    expect(delta.full).not.toBeNull();
    expect(delta.full!.frames.length).toBe(1);
    expect(delta.full!.frames[0].id).toBe(1);
  });
});
